// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKypFZ0g7huxj9E24H7KjepMJT_2hyOs',
    appId: '1:171734850253:web:75373b2f57d584294d2784',
    messagingSenderId: '171734850253',
    projectId: 'yourcity-1bfd8',
    authDomain: 'yourcity-1bfd8.firebaseapp.com',
    storageBucket: 'yourcity-1bfd8.appspot.com',
    measurementId: 'G-XN9CYZSS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDMDeigXCD4aW3zUhnPaQAFQSkih3vgo',
    appId: '1:171734850253:android:5614bf2610c549134d2784',
    messagingSenderId: '171734850253',
    projectId: 'yourcity-1bfd8',
    storageBucket: 'yourcity-1bfd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PnFXllbJbRcBV5Cy-m00dOiMtSqLNps',
    appId: '1:171734850253:ios:27c4f230151aa9a24d2784',
    messagingSenderId: '171734850253',
    projectId: 'yourcity-1bfd8',
    storageBucket: 'yourcity-1bfd8.appspot.com',
    iosBundleId: 'com.example.licenseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-PnFXllbJbRcBV5Cy-m00dOiMtSqLNps',
    appId: '1:171734850253:ios:2574229b23e83e2c4d2784',
    messagingSenderId: '171734850253',
    projectId: 'yourcity-1bfd8',
    storageBucket: 'yourcity-1bfd8.appspot.com',
    iosBundleId: 'com.example.licenseProject.RunnerTests',
  );
}
